
theme: jekyll-theme-minimal
title: Encoding the Vandegrifter
description: A Digital Edition of Fanny Van de Grift Stevenson’s Unpublished Short Stories

<ul>
   <li><a href="https://robynpritzker.github.io/encodingvandegrifter/borriballoo.html">Home</a></li>
   <li><a href="https://robynpritzker.github.io/encodingvandegrifter/sheep.html">Stories</a></li>
   <li><a href="https://robynpritzker.github.io/encodingvandegrifter/hunchback.html">Manuscripts</a></li>
   <li><a href="https://robynpritzker.github.io/encodingvandegrifter/ahchoon.html">About</a></li>
</ul>	


  

