
theme: jekyll-theme-minimal
title: <a href="https://robynpritzker.github.io/encodingvandegrifter/"><img src="https://robynpritzker.github.io/encodingvandegrifter/logo.png" style="height:300px"></a>
description: A Digital Edition of Fanny Van de Grift Stevenson’s Unpublished Short Stories <br/> <br/><a href="https://robynpritzker.github.io/encodingvandegrifter/">[home]</a> <br/> <br/><a href="https://robynpritzker.github.io/encodingvandegrifter/storiesIndex.html">[stories]</a> <br/> <br/> <a href="https://robynpritzker.github.io/encodingvandegrifter/imagesIndex.html">[manuscripts]</a> <br/><br/> <a href="https://robynpritzker.github.io/encodingvandegrifter/aboutIndex.html">[about]</a><br/><br/>Robyn Pritzker, 2019. <br/>Centre for Data, Culture, and Society. <br/>University of Edinburgh.


