
theme: jekyll-theme-minimal
title: Encoding the Vandegrifter
description: A Digital Edition of Fanny Van de Grift Stevenson’s Unpublished Short Stories <br/> <br/> <a href="https://robynpritzker.github.io/encodingvandegrifter/storiesIndex.html">Stories</a> <br/> <br/> Robyn Pritzker, 2019. Centre for Data, Culture, and Society. University of Edinburgh.




  

